In [1]:
import numpy as np 

#### Defining input and output features

In [7]:
X = np.array([
    [1,0.5,87.5,100],
    [1,1.5,100,100],
     [1,1.5,75,57.14],
     [1,1,50,80],
     [1,1.5,72.22,75],
     [1,2,77.78,87.50]
])
Y =  np.array([38.84,45.5,35.08,34.62,30.972,39.66])

In [8]:
X,Y

(array([[  1.  ,   0.5 ,  87.5 , 100.  ],
        [  1.  ,   1.5 , 100.  , 100.  ],
        [  1.  ,   1.5 ,  75.  ,  57.14],
        [  1.  ,   1.  ,  50.  ,  80.  ],
        [  1.  ,   1.5 ,  72.22,  75.  ],
        [  1.  ,   2.  ,  77.78,  87.5 ]]),
 array([38.84 , 45.5  , 35.08 , 34.62 , 30.972, 39.66 ]))

#### Performing matrix operations and calculating errors

In [18]:
Xt = X.transpose()

In [20]:
Xt

array([[  1.  ,   1.  ,   1.  ,   1.  ,   1.  ,   1.  ],
       [  0.5 ,   1.5 ,   1.5 ,   1.  ,   1.5 ,   2.  ],
       [ 87.5 , 100.  ,  75.  ,  50.  ,  72.22,  77.78],
       [100.  , 100.  ,  57.14,  80.  ,  75.  ,  87.5 ]])

In [19]:
Xt.shape

(4, 6)

In [34]:
XtX =  np.dot(Xt,X)

In [32]:
XtX.shape

(4, 4)

In [33]:
XtX

array([[6.000000e+00, 8.000000e+00, 4.625000e+02, 4.996400e+02],
       [8.000000e+00, 1.200000e+01, 6.201400e+02, 6.532100e+02],
       [4.625000e+02, 6.201400e+02, 3.704671e+04, 3.925775e+04],
       [4.996400e+02, 6.532100e+02, 3.925775e+04, 4.294623e+04]])

In [35]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 9.29568551e+00, -1.65344522e+00, -1.34183255e-02,
        -7.07320787e-02],
       [-1.65344522e+00,  9.16118118e-01, -9.95637404e-03,
         1.44034692e-02],
       [-1.34183255e-02, -9.95637404e-03,  1.12589099e-03,
        -7.21646856e-04],
       [-7.07320787e-02,  1.44034692e-02, -7.21646856e-04,
         1.28677926e-03]])

In [36]:
final_X = np.dot(XtX_inv,Xt)
final_X

array([[ 2.21651555e-01, -1.59952273e+00,  1.76751230e+00,
         1.31275773e+00,  5.41540318e-01, -1.24393916e+00],
       [-6.26221967e-01,  1.65441476e-01, -2.02981863e-01,
        -8.28682650e-02,  8.19428170e-02,  6.64687802e-01],
       [ 7.95426306e-03,  1.20715263e-02,  1.48540359e-02,
        -2.48118988e-02, -1.16455384e-03, -8.90337269e-03],
       [ 2.00348199e-03,  7.38636550e-03, -2.97238222e-02,
         1.05313885e-02, -4.73576633e-03,  1.45383525e-02]])

In [38]:
 beta = final_X @ Y

In [39]:
beta

array([10.72062542,  2.11507403,  0.13111335,  0.16569476])

In [40]:
y_pred =  X @ beta
y_pred

array([39.82005677, 43.57404764, 33.19453635, 32.64694798, 35.78934974,
       39.64706152])

In [42]:
residuals = Y - y_pred
residuals

array([-0.98005677,  1.92595236,  1.88546365,  1.97305202, -4.81734974,
        0.01293848])

##### Residual error is the difference between the actual observed value and the value predicted by the regression model.

In [46]:
RSS = np.sum(residuals ** 2)
print(RSS)

35.32473716457472


Mean Squared Error (MSE) is the average of the squares of the residual errors between the actual values and the predicted values in a regression model.

In [48]:
MSE = RSS / 6
print(MSE)

5.887456194095787
